easy_admin:
    disabled_actions: ['new']
    entities:
        Contact_clients:
            class: App\Entity\Contact
            list:
                fields:
                    - { property: 'nom'}
                    - { property: 'societe'}
                    - { property: 'numero'}
                    - { property: 'email'}
                    - { property: 'message'}
                    - { property: 'document', template: 'contract.html.twig', base_path: '%kernel.project_dir%' }


    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'

